# Generated by Django 5.2.17 on 2026-09-26 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=12, unique=True, verbose_name='學號')),
                ('program', models.CharField(default='學士班', max_length=20, verbose_name='學制')),
                ('dept', models.CharField(max_length=40, verbose_name='系所')),
                ('college', models.CharField(blank=True, max_length=40, verbose_name='學院')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='年級')),
                ('cls', models.CharField(blank=True, max_length=4, verbose_name='班別')),
                ('campus', models.CharField(blank=True, max_length=20, verbose_name='校區')),
                ('is_demo', models.BooleanField(default=True, verbose_name='示範帳號')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='帳號')),
            ],
            options={
                'verbose_name': '學生資料',
                'verbose_name_plural': '學生資料',
            },
        ),
    ]
