# Generated by Django 5.2.17 on 2026-09-26 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='啟用')),
                ('now', models.DateTimeField(verbose_name='示範的現在時間')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='說明')),
            ],
            options={
                'verbose_name': '示範時鐘',
                'verbose_name_plural': '示範時鐘',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=6, verbose_name='學期')),
                ('demo_now', models.DateTimeField(verbose_name='示範時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='實際時間')),
                ('ok', models.BooleanField(verbose_name='成功')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='HTTP 狀態碼')),
                ('added', models.JSONField(default=list, verbose_name='加選')),
                ('dropped', models.JSONField(default=list, verbose_name='退選')),
                ('reasons', models.JSONField(default=list, verbose_name='原因')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='學生帳號')),
            ],
            options={
                'verbose_name': '送出紀錄',
                'verbose_name_plural': '送出紀錄',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_index=True, max_length=6, verbose_name='學期')),
                ('course_key', models.CharField(max_length=60, verbose_name='課程鍵（選課編號）')),
                ('action', models.CharField(choices=[('add', '加選'), ('drop', '退選')], max_length=4, verbose_name='動作')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='學生帳號')),
            ],
            options={
                'verbose_name': '選課車',
                'verbose_name_plural': '選課車',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'semester', 'course_key'), name='uniq_cart_item')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_index=True, max_length=6, verbose_name='學期')),
                ('course_key', models.CharField(max_length=60, verbose_name='課程鍵（選課編號）')),
                ('source', models.CharField(choices=[('seed', '示範初始課表'), ('submit', '送出選課')], default='submit', max_length=8, verbose_name='來源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='學生帳號')),
            ],
            options={
                'verbose_name': '我的課表（已選上）',
                'verbose_name_plural': '我的課表（已選上）',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'semester', 'course_key'), name='uniq_enrollment')],
            },
        ),
    ]
