# Generated by Django 5.2.17 on 2026-09-26 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=40, verbose_name='來源')),
                ('started_at', models.DateTimeField(verbose_name='開始')),
                ('finished_at', models.DateTimeField(auto_now_add=True, verbose_name='結束')),
                ('status', models.CharField(max_length=10, verbose_name='狀態')),
                ('n_items', models.IntegerField(default=0, verbose_name='筆數')),
                ('message', models.TextField(blank=True, verbose_name='訊息')),
            ],
            options={
                'verbose_name': '行事曆／公告爬蟲紀錄',
                'verbose_name_plural': '行事曆／公告爬蟲紀錄',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='news', max_length=40, verbose_name='來源')),
                ('news_id', models.CharField(max_length=40, verbose_name='公告編號')),
                ('title', models.CharField(max_length=500, verbose_name='標題')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='登刊日期')),
                ('unit', models.CharField(blank=True, max_length=60, verbose_name='發布單位')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='網站分類')),
                ('tag', models.CharField(blank=True, max_length=8, verbose_name='關鍵字分類')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='網址')),
                ('hash', models.CharField(max_length=40)),
                ('fetched_at', models.DateTimeField(verbose_name='抓取時間')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次看到')),
            ],
            options={
                'verbose_name': '校園公告',
                'verbose_name_plural': '校園公告',
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('source_name', 'news_id'), name='uniq_ann_source_id')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=40, verbose_name='來源')),
                ('uid', models.CharField(max_length=200, verbose_name='來源內唯一鍵')),
                ('title', models.CharField(max_length=300, verbose_name='標題')),
                ('category', models.CharField(choices=[('選課', '選課'), ('繳費', '繳費'), ('考試', '考試'), ('放假', '放假'), ('獎助學金', '獎助學金'), ('學校', '學校'), ('公告', '公告')], db_index=True, max_length=8, verbose_name='分類')),
                ('start_date', models.DateField(db_index=True, verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日（含）')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='來源網址')),
                ('raw_text', models.TextField(blank=True, verbose_name='原始文字')),
                ('hash', models.CharField(db_index=True, max_length=40)),
                ('semester', models.CharField(blank=True, db_index=True, max_length=8, verbose_name='學期')),
                ('audience', models.CharField(default='student', max_length=10, verbose_name='對象')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('fetched_at', models.DateTimeField(verbose_name='抓取時間')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次看到')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '行事曆事件',
                'verbose_name_plural': '行事曆事件',
                'ordering': ['start_date', 'end_date'],
                'constraints': [models.UniqueConstraint(fields=('source_name', 'uid'), name='uniq_event_source_uid')],
            },
        ),
    ]
