# Generated by Django 5.2.17 on 2026-09-26 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_index=True, max_length=6, verbose_name='學期')),
                ('scraped_at', models.DateTimeField(verbose_name='抓取時間')),
                ('course_code', models.CharField(db_index=True, max_length=12, verbose_name='科目代碼')),
                ('selection_no', models.CharField(blank=True, max_length=8, verbose_name='選課編號')),
                ('offering_key', models.CharField(max_length=60, verbose_name='課程鍵')),
                ('name', models.CharField(max_length=200, verbose_name='課名')),
                ('offering_class', models.CharField(blank=True, max_length=30, verbose_name='開課班級')),
                ('group_name', models.CharField(blank=True, max_length=60, verbose_name='組別')),
                ('term_type', models.CharField(blank=True, max_length=2, verbose_name='全/單')),
                ('credits', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='學分')),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='時數')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='人數上限')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='教師')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('plan_url', models.URLField(blank=True, max_length=500, verbose_name='授課計畫')),
                ('teacher_url', models.URLField(blank=True, max_length=500)),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='其他欄位')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'ordering': ['course_code', 'selection_no'],
            },
        ),
        migrations.CreateModel(
            name='CourseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_index=True, max_length=6, verbose_name='學期')),
                ('course_code', models.CharField(db_index=True, max_length=12, verbose_name='科目代碼')),
                ('rule_code', models.CharField(blank=True, max_length=4)),
                ('description', models.CharField(blank=True, max_length=60, verbose_name='說明')),
                ('phase', models.CharField(blank=True, max_length=4, verbose_name='階段')),
                ('allow', models.BooleanField(null=True, verbose_name='可選')),
                ('dimension', models.CharField(blank=True, max_length=20, verbose_name='條件類型')),
                ('values', models.JSONField(default=list, verbose_name='條件值')),
                ('exceptions', models.JSONField(default=list, verbose_name='例外')),
                ('raw', models.TextField(blank=True)),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '選課限制（原始列）',
                'verbose_name_plural': '選課限制（原始列）',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_index=True, max_length=6, verbose_name='學期')),
                ('scraped_at', models.DateTimeField(verbose_name='抓取時間')),
                ('code', models.CharField(max_length=2, verbose_name='代碼')),
                ('form_value', models.CharField(max_length=40, verbose_name='表單值')),
                ('label', models.CharField(max_length=40, verbose_name='學制')),
            ],
            options={
                'verbose_name': '學制',
                'verbose_name_plural': '學制',
                'ordering': ['semester', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_index=True, max_length=6, verbose_name='學期')),
                ('started_at', models.DateTimeField(verbose_name='開始時間')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('status', models.CharField(choices=[('running', '執行中'), ('ok', '成功'), ('failed', '失敗')], default='running', max_length=10, verbose_name='狀態')),
                ('is_full', models.BooleanField(default=False, verbose_name='全校完整抓取')),
                ('n_classes', models.PositiveIntegerField(default=0, verbose_name='班級數')),
                ('n_requests', models.PositiveIntegerField(default=0, verbose_name='HTTP 請求數')),
                ('raw_dir', models.CharField(blank=True, max_length=500, verbose_name='原始 HTML 資料夾')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '爬蟲執行紀錄',
                'verbose_name_plural': '爬蟲執行紀錄',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_elective', models.CharField(blank=True, max_length=2, verbose_name='必/選')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.course', verbose_name='課程')),
            ],
            options={
                'verbose_name': '班級課表列',
                'verbose_name_plural': '班級課表列',
            },
        ),
        migrations.CreateModel(
            name='CourseRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=6, verbose_name='學期')),
                ('course_code', models.CharField(db_index=True, max_length=12, verbose_name='科目代碼')),
                ('min_grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最低年級')),
                ('max_grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最高年級')),
                ('grades', models.JSONField(blank=True, null=True, verbose_name='限年級')),
                ('dept_only', models.JSONField(blank=True, null=True, verbose_name='限系所')),
                ('program_only', models.JSONField(blank=True, null=True, verbose_name='限學制')),
                ('class_only', models.JSONField(blank=True, null=True, verbose_name='限班級')),
                ('dept_exclude', models.JSONField(blank=True, null=True, verbose_name='不可選學系')),
                ('exceptions', models.JSONField(blank=True, null=True, verbose_name='例外身分')),
                ('other_text', models.TextField(blank=True, verbose_name='其他')),
                ('source', models.CharField(choices=[('selrule', 'Selrule'), ('note', 'Note'), ('selrule+note', 'Both'), ('none', 'None')], default='none', max_length=14, verbose_name='來源')),
                ('rules_checked', models.BooleanField(default=False, verbose_name='已查學校限修資料')),
                ('scraped_at', models.DateTimeField()),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='其他欄位')),
            ],
            options={
                'verbose_name': '限修條件',
                'verbose_name_plural': '限修條件',
                'constraints': [models.UniqueConstraint(fields=('semester', 'course_code'), name='uniq_restriction')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_index=True, max_length=6, verbose_name='學期')),
                ('scraped_at', models.DateTimeField(verbose_name='抓取時間')),
                ('form_value', models.CharField(max_length=60, verbose_name='表單值')),
                ('label', models.CharField(max_length=60, verbose_name='系所／類別')),
                ('class_key', models.CharField(max_length=6)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='timetable.program', verbose_name='學制')),
                ('scrape_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timetable.scraperun')),
            ],
            options={
                'verbose_name': '系所',
                'verbose_name_plural': '系所',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(db_index=True, max_length=6, verbose_name='學期')),
                ('scraped_at', models.DateTimeField(verbose_name='抓取時間')),
                ('form_value', models.CharField(max_length=40, verbose_name='表單值')),
                ('label', models.CharField(max_length=30, verbose_name='班級')),
                ('abbr', models.CharField(blank=True, max_length=20, verbose_name='簡稱')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年級')),
                ('section', models.CharField(blank=True, max_length=2, verbose_name='班別')),
                ('timetable_scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='課表抓取時間')),
                ('courses', models.ManyToManyField(related_name='classes', through='timetable.ClassCourse', to='timetable.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='timetable.department', verbose_name='系所')),
                ('scrape_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timetable.scraperun')),
            ],
            options={
                'verbose_name': '班級',
                'verbose_name_plural': '班級',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='classcourse',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.schoolclass', verbose_name='班級'),
        ),
        migrations.AddField(
            model_name='program',
            name='scrape_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timetable.scraperun'),
        ),
        migrations.AddField(
            model_name='course',
            name='scrape_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='timetable.scraperun'),
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(1, '一'), (2, '二'), (3, '三'), (4, '四'), (5, '五'), (6, '六'), (7, '日')], null=True, verbose_name='星期')),
                ('periods', models.CharField(blank=True, max_length=16, verbose_name='節次')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='結束')),
                ('week_type', models.CharField(blank=True, max_length=2, verbose_name='單雙週')),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='教室')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='教師')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='timetable.course', verbose_name='課程')),
            ],
            options={
                'verbose_name': '上課時段',
                'verbose_name_plural': '上課時段',
                'constraints': [models.UniqueConstraint(fields=('course', 'weekday', 'periods', 'room', 'week_type'), name='uniq_session')],
            },
        ),
        migrations.AddConstraint(
            model_name='classcourse',
            constraint=models.UniqueConstraint(fields=('school_class', 'course'), name='uniq_class_course'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['semester', 'label'], name='timetable_s_semeste_ae6112_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('semester', 'department', 'form_value'), name='uniq_class'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('semester', 'code'), name='uniq_program'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('semester', 'program', 'form_value'), name='uniq_dept'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['semester', 'offering_key'], name='timetable_c_semeste_65fcfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('semester', 'course_code', 'offering_key'), name='uniq_course'),
        ),
    ]
